services:
  edgeever:
    image: ccr.ccs.tencentyun.com/edgeever/edgeever:v1.45.1
    container_name: edgeever
    restart: unless-stopped
    init: true
    ports:
      - "${TRIM_SERVICE_PORT}:8787"
    environment:
      EDGE_EVER_AUTH_USERNAME: "${EDGE_EVER_AUTH_USERNAME:-admin}"
      EDGE_EVER_AUTH_PASSWORD: "${EDGE_EVER_AUTH_PASSWORD}"
    volumes:
      - "${TRIM_DATA_SHARE_PATHS}:/data"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    stop_grace_period: 30s
